## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [4]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("WeatherPy_vacation.csv")
vacation_df.head()

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,3,Hilo,US,80.60,broken clouds,19.73,-155.09,Hilo Hawaiian Hotel
1,8,Tasgaon,IN,81.57,broken clouds,17.03,74.60,Rajan Patil Mala
2,9,Vaini,TO,77.00,few clouds,-21.20,-175.20,Keleti Beach Resort
3,10,Saint-Philippe,RE,75.20,scattered clouds,-21.36,55.77,"Chambres d'hôte ""La Trinité"""
4,24,Ixtapa,MX,82.40,overcast clouds,20.70,-105.20,Container Inn Puerto Vallarta

In [6]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [8]:
# 4a. Add a marker layer for each city to the map.

locations = vacation_df[["Lat", "Lng"]]
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 4b. Display the figure

fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
china_df=vacation_df.loc[(vacation_df['Country']=='CN')]
china_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
13,65,Yueyang,CN,77.40,overcast clouds,29.33,113.09,Delong Fortune Hotel
14,67,Enshi,CN,88.99,overcast clouds,30.30,109.48,Moevenpick Enshi
48,190,Shulan,CN,78.26,broken clouds,44.42,126.95,Shulan Hotel
129,412,Dengfeng,CN,87.40,overcast clouds,34.46,113.03,Songshan Dihao Hotel
142,460,Nanzhang,CN,87.89,overcast clouds,31.78,111.84,Longmenkezhan
146,466,Ankang,CN,86.20,broken clouds,32.68,109.02,安琪酒店
150,472,Beipiao,CN,86.68,overcast clouds,41.79,120.78,Beipiao Hotel
169,529,Songjianghe,CN,76.91,light rain,42.19,127.48,Sijisheng Fashion Guest House
189,576,Dandong,CN,81.36,light rain,40.13,124.39,Yiranju Farmstay
204,628,Erenhot,CN,84.94,clear sky,43.65,111.98,Erenhot Rurouni Youth Hostel
209,640,Fuling,CN,85.30,broken clouds,29.70,107.39,Yingbin Hostel
210,649,Huangcun,CN,88.00,light rain,30.01,118.40,NaN
220,685,Tanggu,CN,89.60,overcast clouds,39.02,117.65,Ibis Tianjin Tanggu Hotel

In [46]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.
vacation_start = vacation_df.loc[150]
vacation_end = vacation_df.loc[150]
vacation_stop1 = vacation_df.loc[169]
vacation_stop2 = vacation_df.loc[189] 
vacation_stop3 = vacation_df.loc[48] 

four_cities_df=vacation_df.loc[[150,169,189,48],:]
four_cities_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
150,472,Beipiao,CN,86.68,overcast clouds,41.79,120.78,Beipiao Hotel
169,529,Songjianghe,CN,76.91,light rain,42.19,127.48,Sijisheng Fashion Guest House
189,576,Dandong,CN,81.36,light rain,40.13,124.39,Yiranju Farmstay
48,190,Shulan,CN,78.26,broken clouds,44.42,126.95,Shulan Hotel

In [37]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = (vacation_start[5], vacation_start[6])
end = (vacation_end[5], vacation_end[6])
stop1 = (vacation_stop1[5], vacation_stop1[6])
stop2 = (vacation_stop2[5], vacation_stop2[6])
stop3 = (vacation_stop3[5], vacation_stop3[6])

In [40]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
fig = gmaps.figure()
route = gmaps.directions_layer(start,end,waypoints=[stop3,stop1,stop2],travel_mode='DRIVING')
fig.add_layer(route)

fig

Figure(layout=FigureLayout(height='420px'))

In [47]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
#itinerary_df = pd.concat([vacation_start,vacation_stop1,vacation_stop2,vacation_stop3],ignore_index=False)
#itinerary_df
four_cities_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
150,472,Beipiao,CN,86.68,overcast clouds,41.79,120.78,Beipiao Hotel
169,529,Songjianghe,CN,76.91,light rain,42.19,127.48,Sijisheng Fashion Guest House
189,576,Dandong,CN,81.36,light rain,40.13,124.39,Yiranju Farmstay
48,190,Shulan,CN,78.26,broken clouds,44.42,126.95,Shulan Hotel

In [48]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>

"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in four_cities_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = four_cities_df[["Lat", "Lng"]]

In [49]:
# 11a. Add a marker layer for each city to the map.
locations = four_cities_df[["Lat", "Lng"]]
max_temp = four_cities_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))